version: "3.8"

services:
    db:
        container_name: mysql
        restart: always
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
volumes:
    data: